# Generated by Django 4.1.6 on 2023-02-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stores',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
