# Generated by Django 4.1.6 on 2023-02-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stores_confirmed_alter_stores_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
