# Generated by Django 4.1.6 on 2023-02-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_clients_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='password_hash',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password_salt',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='stores',
            name='password_hash',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='stores',
            name='password_salt',
            field=models.BinaryField(),
        ),
    ]
