# Generated by Django 4.1.6 on 2023-02-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_clients_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='password_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password_salt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stores',
            name='password_hash',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stores',
            name='password_salt',
            field=models.TextField(),
        ),
    ]
