# Generated by Django 4.1.6 on 2023-02-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clients_image_bytes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-creation']},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-creation']},
        ),
        migrations.AlterModelOptions(
            name='packs',
            options={'ordering': ['-creation']},
        ),
        migrations.AlterModelOptions(
            name='ratings',
            options={'ordering': ['-creation']},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'ordering': ['-creation']},
        ),
    ]
