# Generated by Django 4.1.6 on 2023-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_clients_options_alter_orders_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='packs',
            name='pack_type',
            field=models.CharField(choices=[('fast_food', 'Fast food'), ('dessert', 'Dessert'), ('random', 'Random')], default='random', max_length=20),
        ),
    ]
