# Generated by Django 4.1.6 on 2023-02-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orders_status_alter_packs_pack_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='image_bytes',
            field=models.ImageField(max_length=10000, null=True, upload_to=''),
        ),
    ]
