# Generated by Django 4.1.6 on 2023-02-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_clients_image_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='image_bytes',
            field=models.ImageField(max_length=10000, null=True, upload_to=''),
        ),
    ]
