# Generated by Django 4.1.6 on 2023-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_stores_image_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stores',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
