# Generated by Django 4.1.6 on 2023-04-06 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_stores_latitude_stores_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='image_bytes',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
