# Generated by Django 4.1.6 on 2023-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_packs_image_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packs',
            name='image_bytes',
            field=models.ImageField(max_length=30000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stores',
            name='image_bytes',
            field=models.ImageField(max_length=30000, null=True, upload_to=''),
        ),
    ]
