# Generated by Django 4.1.6 on 2023-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_packs_image_bytes_alter_stores_image_bytes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='image_bytes',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='stores',
            name='image_bytes',
            field=models.BinaryField(null=True),
        ),
    ]
