# This docker compose will be used by API developers since it
# only starts the Databases and expose their ports

version: "3.3"

networks:
  dealer:
    external: false

services:
  redis:
    networks:
      - dealer
    container_name: dealer-redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    networks:
      - dealer
    container_name: dealer-postgres
    restart: unless-stopped
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # Django handles everything for us, no database management required
      # - type: bind
      #   source: ./docker-entrypoint-initdb.d
      #   target: /docker-entrypoint-initdb.d
      #   read_only: true
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dealer
      POSTGRES_USER: dealer
      POSTGRES_PASSWORD: dealer
  dealer-api:
    networks:
      - dealer
    container_name: dealer-api
    restart: unless-stopped
    image: dealer:latest
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      SECRET_KEY: "development-secret"
      POSTGRES_DATABASE: "dealer"
      POSTGRES_USERNAME: "dealer"
      POSTGRES_PASSWORD: "dealer"
      POSTGRES_HOST: "dealer-postgres"
      POSTGRES_PORT: "5432"
      REDIS_LEADER: "redis://dealer-redis:6379"
