name: Deploy

on:
  registry_package:
    types: ["published"]

permissions: read-all

jobs:
  deploy_:
    runs-on: kube-master
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PACKAGES_WRITE_PERMISSION }}
          repository: ReSupplyOrg/infrastructure
      - name: Deploy to kubernetes cluster
        run: KUBECONFIG=/opt/runner/kubeconfig.yaml kubectl -n resupply apply dealer/deployment.yaml
